drop table test_table if exists;
drop table lots_of_rows if exists;

create table test_table (
 	id bigint generated by default as identity, 
	name varchar(50) not null,
	int_value int null,
	double_value double null,
	decimal_value decimal(5,2),
	bigint_value bigint null,
	date_value date null,
	time_value time null,
	datetime_value datetime null,
	bigtext_value TEXT null,
	clob_value clob null,
	primary key (id)
);

create table random_names (
 	id bigint generated by default as identity, 
	first varchar(50) not null,
	last varchar(50) not null,
	control_index int not null
);